qwerty: source/editor.h File Reference
source/editor.h File Reference
#include "tty.h"
#include "screen.h"
Data Structures
struct _editor
Defines
#define BACKUP_TIMEOUT 5
Typedefs
typedef struct _editor Editor
Functions
void editor_handle_sigint (int signum)
uint8_t editor_init (Editor *editor, const char *tgt)
void editor_release (Editor *editor)
void editor_load_from_file (Editor *editor)
void editor_loopy (Editor *editor)
uint8_t editor_safe_exit (Editor *editor)
void editor_input (Editor *editor, const unsigned char in)
unsigned char editor_getch ()
void editor_flush (Editor *editor, const char *fname, FILE *sink)
void editor_perform_backup (int signum)
Variables
Editor * gEditor
Define Documentation
#define BACKUP_TIMEOUT 5
Definition at line 7 of file editor.h.
Referenced by editor_loopy(), and editor_perform_backup().
Typedef Documentation
typedef struct _editor Editor
Represents an editor-session
Function Documentation
void editor_flush (Editor * editor, const char * fname, FILE * sink)
Flush lines to specified file
Definition at line 375 of file editor.c.
References _tty_line_buffer::buffer, _editor::head, _tty_line_buffer::length, _tty_line_buffer_list::line, and _tty_line_buffer_list::next.
Referenced by editor_input(), and editor_safe_exit().
unsigned char editor_getch ()
Grab a character
Definition at line 331 of file editor.c.
Referenced by editor_input(), editor_loopy(), and editor_safe_exit().
void editor_handle_sigint (int signum)
Callback to handle SIGINT
Definition at line 316 of file editor.c.
References editor_handle_sigint(), editor_release(), editor_safe_exit(), _editor::screen, screen_add_menu(), and screen_flush_out().
Referenced by editor_handle_sigint(), and editor_loopy().
uint8_t editor_init (Editor * editor, const char * tgt)
Initialize editor
Definition at line 13 of file editor.c.
References _editor::backup, _tty_info::cols, _editor::cur, editor_load_from_file(), _editor::filename, _editor::head, _editor::is_dirty, _tty_info::rows, _editor::screen, screen_init(), screen_new(), _editor::target, _editor::tempname, tty_info_get(), tty_line_buffer_list_init(), and _editor::ttyInfo.
Referenced by main().
void editor_input (Editor * editor, const unsigned char in)
Respond to input
Definition at line 103 of file editor.c.
References _editor::backup, _tty_line_buffer::buffer, _editor::cur, DO_AUTO_BACKUP, editor_flush(), editor_getch(), _editor::filename, _editor::head, _tty_line_buffer::insertionPoint, _editor::is_dirty, _tty_line_buffer::length, _tty_line_buffer_list::line, _screen::max_row, _tty_line_buffer_list::next, _tty_line_buffer_list::prev, _editor::screen, screen_add_menu(), screen_advance_row(), screen_ask(), screen_clear_line(), screen_delete(), screen_flush_out(), screen_insert_tab(), screen_insert_tab_here(), screen_move_col_left(), screen_putc(), screen_putc_here(), screen_reset_col(), screen_retreat_row(), screen_set_col(), screen_shift_down(), screen_shift_up(), TAB_SIZE, _editor::target, _editor::tempname, tty_line_buffer_list_del(), tty_line_buffer_list_grab_line_at(), tty_line_buffer_list_length(), and tty_line_buffer_list_new().
Referenced by editor_load_from_file(), and editor_loopy().
void editor_load_from_file (Editor * editor)
Load file contents if content already exists
Definition at line 70 of file editor.c.
References _editor::cur, editor_input(), _editor::head, _editor::screen, screen_reset_col(), screen_set_row_pos(), and _editor::target.
Referenced by editor_init().
void editor_loopy (Editor * editor)
Editor's main loop
Definition at line 86 of file editor.c.
References BACKUP_TIMEOUT, editor_getch(), editor_handle_sigint(), editor_input(), editor_perform_backup(), _editor::screen, and screen_flush_out().
Referenced by main().
void editor_perform_backup (int signum)
Backup data every five seconds
Definition at line 397 of file editor.c.
References BACKUP_TIMEOUT, DO_AUTO_BACKUP, and editor_perform_backup().
Referenced by editor_loopy(), and editor_perform_backup().
void editor_release (Editor * editor)
Cleanup editor session
Definition at line 56 of file editor.c.
References _editor::backup, _editor::head, _editor::screen, screen_release(), _editor::target, _editor::tempname, and tty_line_buffer_list_release().
Referenced by editor_handle_sigint().
uint8_t editor_safe_exit (Editor * editor)
Exit editor safely
Definition at line 287 of file editor.c.
References editor_flush(), editor_getch(), _editor::filename, _editor::is_dirty, _editor::screen, screen_ask(), screen_flush_out(), and _editor::target.
Referenced by editor_handle_sigint().
Variable Documentation
Editor* gEditor
keeps a global reference to current editor
Definition at line 9 of file editor.c.