qwerty: source/screen.c File Reference
source/screen.c File Reference
#include "screen.h"
#include "colours.h"
#include "textproperties.h"
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
Functions
uint8_t screen_new (Screen *screen, const uint16_t rows, const uint16_t cols)
void screen_init (Screen *screen, const unsigned char *filename)
void screen_release (Screen *screen)
uint8_t screen_write (Screen *screen, const unsigned char c)
ScreenState screen_putc (Screen *screen, const unsigned char c)
void screen_putc_here (Screen *screen, const unsigned char c, const uint16_t col)
ScreenState screen_advance_row (Screen *screen)
ScreenState screen_retreat_row (Screen *screen)
ScreenState screen_shift_down (Screen *screen)
ScreenState screen_shift_up (Screen *screen, const char *lastline)
void screen_reset_col (Screen *screen)
ScreenState screen_set_col (Screen *screen, const uint16_t pos)
ScreenState screen_insert_tab (Screen *screen)
ScreenState screen_insert_tab_here (Screen *screen, const uint16_t col)
ScreenState screen_set_row_pos (Screen *screen, const uint16_t pos)
ScreenState screen_move_col_right (Screen *screen)
ScreenState screen_move_col_left (Screen *screen)
void screen_delete (Screen *screen)
void screen_clear_line (Screen *screen)
void screen_update_cursor (Screen *screen)
void screen_flush_out (Screen *screen)
unsigned char screen_ask (Screen *screen, const char *question)
void screen_add_menu (Screen *screen)
Function Documentation
void screen_add_menu (Screen * screen)
Add the menu to the buffer
Definition at line 342 of file screen.c.
References _screen::buffer, _screen::max_col, and _screen::max_row.
Referenced by editor_handle_sigint(), editor_input(), and screen_init().
ScreenState screen_advance_row (Screen * screen)
Advance row. It returns the state of the screen. Supposing that it needs to scroll, the caller has to decide what to do next
Definition at line 153 of file screen.c.
References _screen::max_row, _screen::pos, _screen_pos::row, SCR_NORMAL, and SCR_SCROLL_BOTTOM.
Referenced by editor_input().
unsigned char screen_ask (Screen * screen, const char * question)
Ask for user input in response to question posed
Definition at line 325 of file screen.c.
References _screen::buffer, _screen::max_col, _screen::max_row, _screen::mode, and SCREEN_INTR.
Referenced by editor_input(), and editor_safe_exit().
void screen_clear_line (Screen * screen)
Clear the current line buffer
Definition at line 267 of file screen.c.
References _screen::buffer, _screen::max_col, _screen::pos, and _screen_pos::row.
Referenced by editor_input().
void screen_delete (Screen * screen)
Removes the character (if there exists one) from the current position of the screen buffer
Definition at line 260 of file screen.c.
References _screen::buffer, _screen_pos::col, _screen::pos, and _screen_pos::row.
Referenced by editor_input(), and screen_write().
void screen_flush_out (Screen * screen)
Flush screen buffer to output device
Definition at line 277 of file screen.c.
References _screen::buffer, _screen_pos::col, _screen::max_col, _screen::max_row, _screen::pos, and _screen_pos::row.
Referenced by editor_handle_sigint(), editor_input(), editor_loopy(), and editor_safe_exit().
void screen_init (Screen * screen, const unsigned char * filename)
Initialize screen buffer
Definition at line 33 of file screen.c.
References _screen::buffer, _screen::max_col, _screen::pos, _screen_pos::row, and screen_add_menu().
Referenced by editor_init().
ScreenState screen_insert_tab (Screen * screen)
Insert TAB_SPACE at current position
Definition at line 212 of file screen.c.
References _screen::buffer, _screen_pos::col, _screen::max_col, _screen::pos, _screen_pos::row, SCR_NORMAL, SCR_SCROLL_RIGHT, and TAB_SIZE.
Referenced by editor_input().
ScreenState screen_insert_tab_here (Screen * screen, const uint16_t col)
Insert TAB_SPACE at position
Definition at line 224 of file screen.c.
References _screen::buffer, _screen_pos::col, _screen::max_col, _screen::pos, _screen_pos::row, SCR_NORMAL, SCR_SCROLL_RIGHT, and TAB_SIZE.
Referenced by editor_input().
ScreenState screen_move_col_left (Screen * screen)
Move column position left. The same logic applies to this as screen_advance_row
Definition at line 252 of file screen.c.
References _screen_pos::col, _screen::pos, SCR_NORMAL, and SCR_SCROLL_LEFT.
Referenced by editor_input().
ScreenState screen_move_col_right (Screen * screen)
Move column position right. The same logic applies to this as screen_advance_row
Definition at line 244 of file screen.c.
References _screen_pos::col, _screen::max_col, _screen::pos, SCR_NORMAL, and SCR_SCROLL_RIGHT.
uint8_t screen_new (Screen * screen, const uint16_t rows, const uint16_t cols)
Create a new screen buffer
Definition at line 8 of file screen.c.
References _screen::buffer, _screen_pos::col, _screen::max_col, _screen::max_row, _screen::mode, _screen::pos, _screen_pos::row, and SCREEN_NORMAL.
Referenced by editor_init().
ScreenState screen_putc (Screen * screen, const unsigned char c)
Write a character to the current position in the screen buffer
Definition at line 129 of file screen.c.
References _screen::buffer, _screen_pos::col, _screen::max_col, _screen::pos, _screen_pos::row, SCR_NORMAL, and TAB_SIZE.
Referenced by editor_input().
void screen_putc_here (Screen * screen, const unsigned char c, const uint16_t col)
Write a character to the specified position in the screen buffer
Definition at line 148 of file screen.c.
References _screen::buffer, _screen::pos, and _screen_pos::row.
Referenced by editor_input().
void screen_release (Screen * screen)
Deletes screen buffer
Definition at line 50 of file screen.c.
References _screen::buffer, and _screen::max_row.
Referenced by editor_release().
void screen_reset_col (Screen * screen)
Reset col position to beginning of line
Definition at line 198 of file screen.c.
References _screen_pos::col, and _screen::pos.
Referenced by editor_input(), and editor_load_from_file().
ScreenState screen_retreat_row (Screen * screen)
Retreat row. The same logic applies to this as screen_advance_row
Definition at line 161 of file screen.c.
References _screen::pos, _screen_pos::row, SCR_NORMAL, and SCR_SCROLL_TOP.
Referenced by editor_input().
ScreenState screen_set_col (Screen * screen, const uint16_t pos)
Set col position
Definition at line 203 of file screen.c.
References _screen_pos::col, _screen::max_col, _screen::pos, SCR_NORMAL, and SCR_SCROLL_RIGHT.
Referenced by editor_input().
ScreenState screen_set_row_pos (Screen * screen, const uint16_t pos)
Set row position
Definition at line 236 of file screen.c.
References _screen::max_row, _screen::pos, _screen_pos::row, SCR_NORMAL, and SCR_SCROLL_BOTTOM.
Referenced by editor_load_from_file().
ScreenState screen_shift_down (Screen * screen)
Shifts buffer down by one from the current position
Definition at line 169 of file screen.c.
References _screen::buffer, _screen::max_col, _screen::max_row, _screen::pos, _screen_pos::row, SCR_NORMAL, and SCR_SCROLL_BOTTOM.
Referenced by editor_input().
ScreenState screen_shift_up (Screen * screen, const char * lastline)
Shifts buffer up by one to the current position
Definition at line 185 of file screen.c.
References _screen::buffer, _screen::max_col, _screen::max_row, _screen::pos, _screen_pos::row, and SCR_NORMAL.
Referenced by editor_input().
void screen_update_cursor (Screen * screen)
Update cursor
Definition at line 272 of file screen.c.
uint8_t screen_write (Screen * screen, const unsigned char c)
Writes the character c into the current position of the screen buffer This acts based on the current input
Definition at line 58 of file screen.c.
References _screen::buffer, _screen_pos::col, _screen::max_col, _screen::max_row, _screen::mode, _screen::pos, _screen_pos::row, screen_delete(), and SCREEN_NORMAL.