qwerty: source/tty.c File Reference
source/tty.c File Reference
#include "tty.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/ioctl.h>
Functions
void tty_info_get (TtyInfo *info)
uint8_t tty_line_buffer_new (TtyLineBuffer *line)
void tty_line_buffer_release (TtyLineBuffer *buf)
uint8_t tty_line_buffer_list_init (TtyLineBufferList *head)
uint16_t tty_line_buffer_list_length (TtyLineBufferList *head)
void tty_line_buffer_list_grab_line_at (TtyLineBufferList *head, const uint16_t pos, const char **str)
uint8_t tty_line_buffer_list_new (TtyLineBufferList **cur)
uint8_t tty_line_buffer_list_del (TtyLineBufferList **cur)
void tty_line_buffer_list_release (TtyLineBufferList *head)
Function Documentation
void tty_info_get (TtyInfo * info)
Populates any TtyInfo object given to it
Definition at line 7 of file tty.c.
References _tty_info::cols, and _tty_info::rows.
Referenced by editor_init().
uint8_t tty_line_buffer_list_del (TtyLineBufferList ** cur)
Deletes the current line from the buffer list
Definition at line 118 of file tty.c.
References _tty_line_buffer_list::next, _tty_line_buffer_list::prev, and tty_line_buffer_release().
Referenced by editor_input().
void tty_line_buffer_list_grab_line_at (TtyLineBufferList * head, const uint16_t pos, const char ** str)
Get the line buffer at specified position in list
Definition at line 66 of file tty.c.
References _tty_line_buffer::buffer, and _tty_line_buffer_list::line.
Referenced by editor_input().
uint8_t tty_line_buffer_list_init (TtyLineBufferList * head)
Initializes a list
Definition at line 37 of file tty.c.
References _tty_line_buffer_list::line, _tty_line_buffer_list::next, _tty_line_buffer_list::prev, and tty_line_buffer_new().
Referenced by editor_init().
uint16_t tty_line_buffer_list_length (TtyLineBufferList * head)
Get the number of lines
Definition at line 53 of file tty.c.
References _tty_line_buffer_list::next.
Referenced by editor_input().
uint8_t tty_line_buffer_list_new (TtyLineBufferList ** cur)
Adds a new node to the buffer list and advances the current pointer
Definition at line 80 of file tty.c.
References _tty_line_buffer_list::next, _tty_line_buffer_list::prev, and tty_line_buffer_new().
Referenced by editor_input().
void tty_line_buffer_list_release (TtyLineBufferList * head)
Destroys buffer list
Definition at line 137 of file tty.c.
References _tty_line_buffer_list::next, and tty_line_buffer_release().
Referenced by editor_release().
uint8_t tty_line_buffer_new (TtyLineBuffer * line)
Definition at line 16 of file tty.c.
References _tty_line_buffer::buffer, _tty_line_buffer::insertionPoint, and _tty_line_buffer::length.
Referenced by tty_line_buffer_list_init(), and tty_line_buffer_list_new().
void tty_line_buffer_release (TtyLineBuffer * buf)
Definition at line 30 of file tty.c.
References _tty_line_buffer::buffer.
Referenced by tty_line_buffer_list_del(), and tty_line_buffer_list_release().